export const characterIds = {
  0: "Makoto",
  1: "Taka",
  2: "Byakuya",
  3: "Mondo",
  4: "Leon",
  5: "Hifumi",
  6: "Hiro",
  7: "Sayaka",
  8: "Kyoko",
  9: "Aoi",
  10: "Toko",
  11: "Sakura",
  12: "Celeste",
  13: "Mukuro",
  14: "Chihiro",
  15: "Monokuma",
  16: "Junko",
  17: "Alter Ego",
} as const;
