import { LinscriptFunction } from "../shared/types";

export const speaker: LinscriptFunction = {
  name: "Speaker",
  parameters: [
    {
      name: "speakerId",
      values: {
        0: "Makoto Naegi",
        1: "Kiyotaka Ishimaru",
        2: "Byakuya Togami",
        3: "Mondo Owada",
        4: "Leon Kuwata",
        5: "Hifumi Yamada",
        6: "Yasuhiro Hagakure",
        7: "Sayaka Maizono",
        8: "Kyoko Kirigiri",
        9: "Aoi Asahina",
        10: "Toko Fukawa",
        11: "Sakura Oogami",
        12: "Celeste Ludenberg",
        13: "Junko Enoshima",
        14: "Chihiro Fujisaki",
        15: "Monokuma",
        16: "Junko Enoshima",
        17: "Alter Ego",
        18: "Genocide Jill",
        19: "Headmaster",
        20: "Makoto's Mom",
        21: "Makoto's Dad",
        22: "Makoto's Sister",
        23: "Narrator",
        24: "Kiyotaka-Mondo",
        25: "Daiya Owada",
        // values 26 through 29 are all 'Makoto Naegi'
        30: "???",
        33: "Usami",
        34: "Monokuma Backup",
        35: "Monokuma Backup (R)",
        36: "Monokuma Backup (L)",
        37: "Monokuma Backup (M)",
      },
    },
  ],
};
